// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  solderedDocsSidebar: [
    'welcome',
    {
      type: 'category',
      label: 'General Information',
      // CH340 drivers
      // Soldered board dimensions (LEGO compatible)
      items: [
        {
          type: 'doc',
          id: 'misc/qwiic',
        },
      ],
    },
    {
      type: 'category',
      label: 'Sensors',
      items: [
        {
          type: 'category',
          label: 'LTR-507 Light and Proximity Sensor',
          items: [
            {
              type: 'doc',
              id: 'sensors/ltr-507/ltr-507-overview',
            },
            {
              type: 'doc',
              id: 'sensors/ltr-507/ltr-507-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/ltr-507/ltr-507-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/ltr-507/arduino_library/ltr-507-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/ltr-507/arduino_library/ltr-507-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/ltr-507/arduino_library/ltr-507-arduino-3',
                },
                {
                  type: 'doc',
                  id: 'sensors/ltr-507/arduino_library/ltr-507-arduino-4',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'BMP180 Pressure & Temperature Sensor',
          items: [
            {
              type: 'doc',
              id: 'sensors/bmp180/bmp180-overview',
            },
            {
              type: 'doc',
              id: 'sensors/bmp180/bmp180-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/bmp180/bmp180-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/bmp180/arduino_library/bmp180-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/bmp180/arduino_library/bmp180-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/bmp180/arduino_library/bmp180-arduino-4',
                },
                {
                  type: 'doc',
                  id: 'sensors/bmp180/arduino_library/bmp180-arduino-5',
                },
                {
                  type: 'doc',
                  id: 'sensors/bmp180/arduino_library/bmp180-arduino-6',
                },
                {
                  type: 'doc',
                  id: 'sensors/bmp180/arduino_library/bmp180-arduino-3',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'BME280 Enviromental Sensor',
          items: [
            {
              type: 'doc',
              id: 'sensors/bme280/bme280-overview',
            },
            {
              type: 'doc',
              id: 'sensors/bme280/bme280-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/bme280/bme280-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/bme280/arduino_library/bme280-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/bme280/arduino_library/bme280-arduino-2',
                },
                
                {
                  type: 'doc',
                  id: 'sensors/bme280/arduino_library/bme280-arduino-3',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'BME680 Enviromental & Air Quality Sensor',
          items: [
            {
              type: 'doc',
              id: 'sensors/bme680/bme680-overview',
            },
            {
              type: 'doc',
              id: 'sensors/bme680/bme680-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/bme680/bme680-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/bme680/arduino_library/bme680-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/bme680/arduino_library/bme680-arduino-5',
                },
                {
                  type: 'doc',
                  id: 'sensors/bme680/arduino_library/bme680-arduino-4',
                },
                {
                  type: 'doc',
                  id: 'sensors/bme680/arduino_library/bme680-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/bme680/arduino_library/bme680-arduino-3',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Hall effect sensor',
          items: [
            {
              type: 'doc',
              id: 'sensors/hall-effect-sensor/hall-effect-sensor-overview',
            },
            {
              type: 'doc',
              id: 'sensors/hall-effect-sensor/hall-effect-sensor-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/hall-effect-sensor/hall-effect-sensor-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/hall-effect-sensor/arduino_library/hall-effect-sensor-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/hall-effect-sensor/arduino_library/hall-effect-sensor-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/hall-effect-sensor/arduino_library/hall-effect-sensor-arduino-3',
                },
                {
                  type: 'doc',
                  id: 'sensors/hall-effect-sensor/arduino_library/hall-effect-sensor-arduino-4',
                },
                {
                  type: 'doc',
                  id: 'sensors/hall-effect-sensor/arduino_library/hall-effect-sensor-arduino-5',
                },
                {
                  type: 'doc',
                  id: 'sensors/hall-effect-sensor/arduino_library/hall-effect-sensor-arduino-6',
                }
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'SHTC3 Temperature and Humidity Sensor',
          items: [
            {
              type: 'doc',
              id: 'sensors/shtc3/shtc3-overview',
            },
            {
              type: 'doc',
              id: 'sensors/shtc3/shtc3-hardware',
            },
            {
              type: 'doc',
              id: 'sensors/shtc3/shtc3-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'sensors/shtc3/arduino_library/shtc3-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'sensors/shtc3/arduino_library/shtc3-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'sensors/shtc3/arduino_library/shtc3-arduino-3',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Actuators',
      items: [
        {
          type: 'category',
          label: 'Smart LED WS2812B',
          items: [
            {
              type: 'doc',
              id: 'actuators/ws2812b/ws2812b-overview',
            },
            {
              type: 'doc',
              id: 'actuators/ws2812b/ws2812b-hardware',
            },
            {
              type: 'doc',
              id: 'actuators/ws2812b/ws2812b-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'actuators/ws2812b/arduino_library/ws2812b-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'actuators/ws2812b/arduino_library/ws2812b-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'actuators/ws2812b/arduino_library/ws2812b-arduino-3',
                },
                {
                  type: 'doc',
                  id: 'actuators/ws2812b/arduino_library/ws2812b-arduino-4',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Basic Stepper Driver',
          items: [
            {
              type: 'doc',
              id: 'actuators/stepper-motor-driver/stepper-motor-driver-overview',
            },
            {
              type: 'doc',
              id: 'actuators/stepper-motor-driver/stepper-motor-driver-hardware',
            },
            {
              type: 'doc',
              id: 'actuators/stepper-motor-driver/stepper-motor-driver-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'actuators/stepper-motor-driver/arduino_library/stepper-motor-driver-arduino-1'
                },
                {
                  type: 'doc',
                  id: 'actuators/stepper-motor-driver/arduino_library/stepper-motor-driver-arduino-2'
                },
                {
                  type: 'doc',
                  id: 'actuators/stepper-motor-driver/arduino_library/stepper-motor-driver-arduino-3'
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Displays',
      items: [
        {
          type: 'category',
          label: 'SSD1306 0.96" I2C OLED Display',
          items: [
            {
              type: 'doc',
              id: 'displays/ssd1306/ssd1306-overview',
            },
            {
              type: 'doc',
              id: 'displays/ssd1306/ssd1306-hardware',
            },
            {
              type: 'doc',
              id: 'displays/ssd1306/ssd1306-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'displays/ssd1306/arduino_library/ssd1306-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'displays/ssd1306/arduino_library/ssd1306-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'displays/ssd1306/arduino_library/ssd1306-arduino-4',
                },
                {
                  type: 'doc',
                  id: 'displays/ssd1306/arduino_library/ssd1306-arduino-5',
                },
                {
                  type: 'doc',
                  id: 'displays/ssd1306/arduino_library/ssd1306-arduino-6',
                },
                {
                  type: 'doc',
                  id: 'displays/ssd1306/arduino_library/ssd1306-arduino-3',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'LCD I2C Displays',
          items: [
            {
              type: 'doc',
              id: 'displays/lcd-i2c/lcd-i2c-overview',
            },
            {
              type: 'doc',
              id: 'displays/lcd-i2c/lcd-i2c-hardware',
            },
            {
              type: 'doc',
              id: 'displays/lcd-i2c/lcd-i2c-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'displays/lcd-i2c/arduino_library/lcd-i2c-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'displays/lcd-i2c/arduino_library/lcd-i2c-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'displays/lcd-i2c/arduino_library/lcd-i2c-arduino-3',
                },
                {
                  type: 'doc',
                  id: 'displays/lcd-i2c/arduino_library/lcd-i2c-arduino-4',
                },
                {
                  type: 'doc',
                  id: 'displays/lcd-i2c/arduino_library/lcd-i2c-arduino-5',
                },
              ],
            },
          ],
        },
      ]
    },
    {
      type: 'category',
      label: 'Communication',
      items: [
        {
          type: 'category',
          label: 'GNSS GPS L86-M33',
          items: [
            {
              type: 'doc',
              id: 'communication/gnss-gps/gnss-gps-overview',
            },
            {
              type: 'doc',
              id: 'communication/gnss-gps/gnss-gps-hardware',
            },
            {
              type: 'doc',
              id: 'communication/gnss-gps/gnss-gps-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'communication/gnss-gps/arduino_library/gnss-gps-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'communication/gnss-gps/arduino_library/gnss-gps-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'communication/gnss-gps/arduino_library/gnss-gps-arduino-3',
                },
                {
                  type: 'doc',
                  id: 'communication/gnss-gps/arduino_library/gnss-gps-arduino-4',
                },
              ],
            },
          ],
        },
        {

          type: 'category',
          label: 'USB-UART CH340 converter',
          items: [
            {
              type: 'doc',
              id: 'communication/ch340/ch340-overview',
            },
            {
              type: 'doc',
              id: 'communication/ch340/ch340-hardware',
            },
            {
              type: 'doc',
              id: 'communication/ch340/ch340-how-it-works',
            },
          ],
        },
        {
          type: 'category',
          label: 'Logic Level Converter',
          items: [
            {
              type: 'doc',
              id: 'communication/logic-level-converter/logic-level-converter-overview',
            },
            {
              type: 'doc',
              id: 'communication/logic-level-converter/logic-level-converter-hardware',
            },
            {
              type: 'doc',
              id: 'communication/logic-level-converter/logic-level-converter-how-it-works',
            },
            {
              type: 'doc',
              id: 'communication/logic-level-converter/logic-level-converter-how-to-connect-it',
            },
          ],
        },
        {
          type: 'category',
          label: 'Logic Level Converter I2C TXS0104',
          items: [
            {
              type: 'doc',
              id: 'communication/txs0104/txs0104-overview',
            },
            {
              type: 'doc',
              id: 'communication/txs0104/txs0104-hardware',
            },
            {
              type: 'doc',
              id: 'communication/txs0104/txs0104-how-it-works',
            },
          ],
        },
        {
          type: 'category',
          label: 'Logic Level Converter TXB0104',
          items: [
            {
              type: 'doc',
              id: 'communication/txb0104/txb0104-overview',
            },
            {
              type: 'doc',
              id: 'communication/txb0104/txb0104-hardware',
            },
            {
              type: 'doc',
              id: 'communication/txb0104/txb0104-how-it-works',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Batteries and Power Supplies',
      items: [
        {
          type: 'category',
          label: '1S Li-Ion Battery Protection',
          items: [
            {
              type: 'doc',
              id: 'batteries and power supplies/battery-protection/battery-protection-overview',
            },
            {
              type: 'doc',
              id: 'batteries and power supplies/battery-protection/battery-protection-hardware',
            },
            {
              type: 'doc',
              id: 'batteries and power supplies/battery-protection/battery-protection-how-it-works',
            },
          ],
        },
      ]
    },
  ],
};

export default sidebars;
