// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  solderedDocsSidebar: [
    'welcome',
    {
      type: 'category',
      label: 'General Information',
      // CH340 drivers
      // Soldered board dimensions (LEGO compatible)
      items: [
        {
          type: 'doc',
          id: 'misc/qwiic',
        },
      ],
    },
    {
      type: 'category',
      label: 'Actuators',
      items: [
        {
          type: 'category',
          label: 'LED-Matrix',
          items: [
            {
              type: 'doc',
              id: 'actuators/led-matrix/led-matrix-overview',
            },
            {
              type: 'doc',
              id: 'actuators/led-matrix/led-matrix-hardware',
            },
            {
              type: 'doc',
              id: 'actuators/led-matrix/led-matrix-how-it-works',
            },
            {
              type: 'category',
              label: 'Arduino library',
              items: [
                {
                  type: 'doc',
                  id: 'actuators/led-matrix/arduino_library/led-matrix-arduino-1',
                },
                {
                  type: 'doc',
                  id: 'actuators/led-matrix/arduino_library/led-matrix-arduino-2',
                },
                {
                  type: 'doc',
                  id: 'actuators/led-matrix/arduino_library/led-matrix-arduino-3',
                },
                {
                  type: 'doc',
                  id: 'actuators/led-matrix/arduino_library/led-matrix-arduino-4',
                },
                {
                  type: 'doc',
                  id: 'actuators/led-matrix/arduino_library/led-matrix-arduino-5',
                },
                {
                  type: 'doc',
                  id: 'actuators/led-matrix/arduino_library/led-matrix-arduino-6',
                },
                {
                  type: 'doc',
                  id: 'actuators/led-matrix/arduino_library/led-matrix-arduino-7',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
